language: c
sudo: false
cache: ccache
addons:
  apt:
    packages:
      - texinfo
env:
  MAKEFLAGS=-j2

os:
  - osx
  - linux
env:
  - FLINT_TAG: v2.6.3
  - FLINT_TAG: v2.7.0
  - FLINT_TAG: trunk

osx_image: xcode6.4

compiler:
  - gcc
  - clang

install:
  - export LOCAL=$(pwd)/local
  - while sleep 30; do echo "still alive"; done &
  - ./.build_dependencies
  - ./configure --with-mpir=${LOCAL} --with-mpfr=${LOCAL} --with-flint=${LOCAL} --prefix=${LOCAL}
  - make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L libantic.dylib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ldd libantic.so; fi

script:
  - make check
  - make install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L local/lib/libantic.dylib; fi
  - PREFIX=$(pwd)/local ./.check_post_install
